apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar20-audiototext-cibuilt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar20-audiototext-cibuilt
  name: mar20-audiototext-cibuilt
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
